

const employeeJson = [
  {
    'name': 'Personal Information',
    'table_name': 'employee',
    'data': [
      {
        'id': 'reference_id',
        'label_name': 'Reference ID',
        'field_name': 'reference_id',
        'related_table': 'employee',
        'status': true,
      },
      {
        'id': 'first_name',
        'label_name': 'Employee First Name',
        'field_name': 'first_name',
        'related_table': 'employee',
        'status': false,
      },
      {
        'id': 'middle_name',
        'label_name': 'Employee Middle Name',
        'field_name': 'middle_name',
        'related_table': 'employee',
        'status': false,
      },
      {
        'id': 'last_name',
        'label_name': 'Employee Last Name',
        'field_name': 'last_name',
        'related_table': 'employee',
        'status': false,
      },
      {
        'id': 'display_name',
        'label_name': 'Employee Name',
        'field_name': 'display_name',
        'related_table': 'employee',
        'status': false,
      },
      {
        'id': 'dob',
        'label_name': 'Date of Birth',
        'field_name': 'dob',
        'related_table': 'employee',
        'status': false,
      },
      {
        'id': 'gender',
        'label_name': 'Gender',
        'field_name': 'gender',
        'related_table': 'employee',
        'status': false,
      },
      {
        'id': 'email_id',
        'label_name': 'Email ID',
        'field_name': 'email_id',
        'related_table': 'employee',
        'status': false,
      },
      {
        'id': 'contact_number',
        'label_name': 'Phone Number',
        'field_name': 'contact_number',
        'related_table': 'employee',
        'status': false,
      },
      {
        'id': 'date_of_joining',
        'label_name': 'Hire Date',
        'field_name': 'date_of_joining',
        'related_table': 'employee',
        'status': false,
      },
      {
        'id': 'role',
        'label_name': 'Employee Designation',
        'field_name': 'name',
        'related_table': 'roles',
        'join_column': 'id',
        'primary_table': 'employee',
        'primary_table_column': 'role_id',
        'status': false,
      },
      {
        'id': 'name',
        'label_name': 'Department',
        'field_name': 'name',
        'related_table': 'departments',
        'join_column': 'id',
        'primary_table': 'employee',
        'primary_table_column': 'department_id',
        'status': false,
      },
      {
        'id': 'name',
        'label_name': 'Employment Type',
        'field_name': 'name',
        'related_table': 'employment_types',
        'join_column': 'id',
        'primary_table': 'employee',
        'primary_table_column': 'employment_type_id',
        'status': false,
      },
      {
        'id': 'name',
        'label_name': 'Reporting to',
        'field_name': 'display_name',
        'related_table': 'employee',
        'join_column': 'id',
        'primary_table': 'employee',
        'primary_table_column': 'reporting_manager_id',
        'status': false,
      },
      {
        'id': 'visa_type',
        'label_name': 'Visa Type',
        'field_name': 'name',
        'related_table': 'visa_types',
        'join_column': 'id',
        'primary_table': 'employee',
        'primary_table_column': 'visa_type_id',
        'status': false,
      },
      {
        'id': 'ssn',
        'label_name': 'SSN',
        'field_name': 'ssn',
        'related_table': 'employee',
        'status': false,
      },
      // {
      //   'id': 'linkedin_url',
      //   'label_name': 'LinkedIn Url',
      //   'field_name': 'linkedin_url',
      //   'related_table': 'employee',
      //   'status': false,
      // },
      // {
      //   'id': 'twitter_url',
      //   'label_name': 'Twitter Url',
      //   'field_name': 'twitter_url',
      //   'related_table': 'employee',
      //   'status': false,
      // },
      {
        'id': 'blood_group',
        'label_name': 'Blood Group',
        'field_name': 'blood_group',
        'related_table': 'employee',
        'status': false,
      },
      {
        'id': 'address1',
        'label_name': 'Address One',
        'field_name': 'address_one',
        'related_table': 'employee_address_details',
        'join_column': 'employee_id',
        'primary_table': 'employee',
        'primary_table_column': 'id',
        'status': false,
      },
      {
        'id': 'address2',
        'label_name': 'Address Two',
        'field_name': 'address_two',
        'related_table': 'employee_address_details',
        'join_column': 'employee_id',
        'primary_table': 'employee',
        'primary_table_column': 'id',
        'status': false,
      },
      {
        'id': 'city',
        'label_name': 'City',
        'field_name': 'city',
        'related_table': 'employee_address_details',
        'join_column': 'employee_id',
        'primary_table': 'employee',
        'primary_table_column': 'id',
        'status': false,
      },
      {
        'id': 'state',
        'label_name': 'State',
        'field_name': 'name',
        'related_table': 'states',
        'join_column': 'id',
        'primary_table': 'employee_address_details',
        'primary_table_column': 'state_id',
        'main_table': 'employee',
        'main_column': 'id',
        'primary_table_main_column': 'employee_id',
        'status': false,
      },
      {
        'id': 'country',
        'label_name': 'Country',
        'field_name': 'name',
        'related_table': 'countries',
        'join_column': 'id',
        'primary_table': 'employee_address_details',
        'primary_table_column': 'country_id',
        'main_table': 'employee',
        'main_column': 'id',
        'primary_table_main_column': 'employee_id',
        'status': false,
      },
      {
        'id': 'zipcode',
        'label_name': 'Zipcode',
        'field_name': 'zip_code',
        'related_table': 'employee_address_details',
        'join_column': 'employee_id',
        'primary_table': 'employee',
        'primary_table_column': 'id',
        'status': false,
      },
    ],
  },
  {
    'name': 'Address Details',
    'table_name': 'employee',
    'data': [
      {
        'id': 'reference_id',
        'label_name': 'Reference ID',
        'field_name': 'reference_id',
        'related_table': 'employee',
        'status': true,
      },
      // {
      //   'id': 'id',
      //   'label_name': 'Employee ID',
      //   'field_name': 'id',
      //   'related_table': 'employee',
      //   'status': false,
      // },
      {
        'id': 'display_name',
        'label_name': 'Employee Name',
        'field_name': 'display_name',
        'related_table': 'employee',
        'status': false,
      },
      // {
      //   'id': 'email_id',
      //   'label_name': 'Email ID',
      //   'field_name': 'email_id',
      //   'related_table': 'employee',
      //   'status': false,
      // },
      // {
      //   'id': 'name',
      //   'label_name': 'Department',
      //   'field_name': 'name',
      //   'related_table': 'departments',
      //   'join_column': 'id',
      //   'primary_table': 'employee',
      //   'primary_table_column': 'department_id',
      //   'status': false,
      // },
      // {
      //   'id': 'name',
      //   'label_name': 'Reporting to',
      //   'field_name': 'display_name',
      //   'related_table': 'employee',
      //   'join_column': 'id',
      //   'primary_table': 'employee',
      //   'primary_table_column': 'reporting_manager_id',
      //   'status': false,
      // },
      // {
      //   'id': 'name',
      //   'label_name': 'Employment Type',
      //   'field_name': 'name',
      //   'related_table': 'employment_types',
      //   'join_column': 'id',
      //   'primary_table': 'employee',
      //   'primary_table_column': 'employment_type_id',
      //   'status': false,
      // },
      {
        'id': 'address1',
        'label_name': 'Address One',
        'field_name': 'address_one',
        'related_table': 'employee_address_details',
        'join_column': 'employee_id',
        'primary_table': 'employee',
        'primary_table_column': 'id',
        'status': false,
      },
      {
        'id': 'address2',
        'label_name': 'Address Two',
        'field_name': 'address_two',
        'related_table': 'employee_address_details',
        'join_column': 'employee_id',
        'primary_table': 'employee',
        'primary_table_column': 'id',
        'status': false,
      },
      {
        'id': 'city',
        'label_name': 'City',
        'field_name': 'city',
        'related_table': 'employee_address_details',
        'join_column': 'employee_id',
        'primary_table': 'employee',
        'primary_table_column': 'id',
        'status': false,
      },
      {
        'id': 'state',
        'label_name': 'State',
        'field_name': 'name',
        'related_table': 'states',
        'join_column': 'id',
        'primary_table': 'employee_address_details',
        'primary_table_column': 'state_id',
        'main_table': 'employee',
        'main_column': 'id',
        'primary_table_main_column': 'employee_id',
        'status': false,
      },
      {
        'id': 'country',
        'label_name': 'Country',
        'field_name': 'name',
        'related_table': 'countries',
        'join_column': 'id',
        'primary_table': 'employee_address_details',
        'primary_table_column': 'country_id',
        'main_table': 'employee',
        'main_column': 'id',
        'primary_table_main_column': 'employee_id',
        'status': false,
      },
      {
        'id': 'zipcode',
        'label_name': 'Zipcode',
        'field_name': 'zip_code',
        'related_table': 'employee_address_details',
        'join_column': 'employee_id',
        'primary_table': 'employee',
        'primary_table_column': 'id',
        'status': false,
      },
    ],
  },
  {
    'name': 'Dependent Details',
    'table_name': 'employee',
    'data': [
      {
        'id': 'reference_id',
        'label_name': 'Reference ID',
        'field_name': 'reference_id',
        'related_table': 'employee',
        'status': true,
      },
      // {
      //   'id': 'id',
      //   'label_name': 'Employee ID',
      //   'field_name': 'id',
      //   'related_table': 'employee',
      //   'status': false,
      // },
      {
        'id': 'display_name',
        'label_name': 'Employee Name',
        'field_name': 'display_name',
        'related_table': 'employee',
        'status': false,
      },
      {
        'id': 'email_id',
        'label_name': 'Email ID',
        'field_name': 'email_id',
        'related_table': 'employee',
        'status': false,
      },
      // {
      //   'id': 'name',
      //   'label_name': 'Department',
      //   'field_name': 'name',
      //   'related_table': 'departments',
      //   'join_column': 'id',
      //   'primary_table': 'employee',
      //   'primary_table_column': 'department_id',
      //   'status': false,
      // },
      // {
      //   'id': 'name',
      //   'label_name': 'Reporting to',
      //   'field_name': 'display_name',
      //   'related_table': 'employee',
      //   'join_column': 'id',
      //   'primary_table': 'employee',
      //   'primary_table_column': 'reporting_manager_id',
      //   'status': false,
      // },
      {
        'id': 'first_name',
        'label_name': 'Dependent First Name',
        'field_name': 'first_name',
        'related_table': 'employee_dependent_details',
        'join_column': 'employee_id',
        'primary_table': 'employee',
        'primary_table_column': 'id',
        'status': false,
      },
      {
        'id': 'last_name',
        'label_name': 'Dependent Last Name',
        'field_name': 'last_name',
        'related_table': 'employee_dependent_details',
        'join_column': 'employee_id',
        'primary_table': 'employee',
        'primary_table_column': 'id',
        'status': false,
      },
      {
        'id': 'name',
        'label_name': 'Relation Type',
        'field_name': 'name',
        'related_table': 'relationship_types',
        'join_column': 'id',
        'primary_table': 'employee_dependent_details',
        'primary_table_column': 'relationship_id',
        'main_table': 'employee',
        'main_column': 'id',
        'primary_table_main_column': 'employee_id',
        'status': false,
      },
      {
        'id': 'dob',
        'label_name': 'Dependent DOB',
        'field_name': 'dob',
        'related_table': 'employee_dependent_details',
        'join_column': 'employee_id',
        'primary_table': 'employee',
        'primary_table_column': 'id',
        'status': false,
      },
      {
        'id': 'name',
        'label_name': 'Dependent Visa Type',
        'field_name': 'name',
        'related_table': 'visa_types',
        'join_column': 'id',
        'primary_table': 'employee_dependent_details',
        'primary_table_column': 'visa_type_id',
        'main_table': 'employee',
        'main_column': 'id',
        'primary_table_main_column': 'employee_id',
        'status': false,
      },
      {
        'id': 'ssn',
        'label_name': 'SSN',
        'field_name': 'ssn',
        'related_table': 'employee_dependent_details',
        'join_column': 'employee_id',
        'primary_table': 'employee',
        'primary_table_column': 'id',
        'status': false,
      },
      {
        'id': 'contact_number',
        'label_name': 'Dependent Contact Number',
        'field_name': 'contact_number ',
        'related_table': 'employee_dependent_details',
        'join_column': 'employee_id',
        'primary_table': 'employee',
        'primary_table_column': 'id',
        'status': false,
      },
      {
        'id': 'email_id',
        'label_name': 'Dependent Email Id',
        'field_name': 'email_id',
        'related_table': 'employee_dependent_details',
        'join_column': 'employee_id',
        'primary_table': 'employee',
        'primary_table_column': 'id',
        'status': false,
      },
    ],
  },
  {
    'name': 'Education Details',
    'table_name': 'employee',
    'data': [
      {
        'id': 'reference_id',
        'label_name': 'Reference ID',
        'field_name': 'reference_id',
        'related_table': 'employee',
        'status': true,
      },
      // {
      //   'id': 'id',
      //   'label_name': 'Employee ID',
      //   'field_name': 'id',
      //   'related_table': 'employee',
      //   'status': false,
      // },
      {
        'id': 'display_name',
        'label_name': 'Employee Name',
        'field_name': 'display_name',
        'related_table': 'employee',
        'status': false,
      },
      {
        'id': 'email_id',
        'label_name': 'Email ID',
        'field_name': 'email_id',
        'related_table': 'employee',
        'status': false,
      },
      // {
      //   'id': 'name',
      //   'label_name': 'Department',
      //   'field_name': 'name',
      //   'related_table': 'departments',
      //   'join_column': 'id',
      //   'primary_table': 'employee',
      //   'primary_table_column': 'department_id',
      //   'status': false,
      // },
      // {
      //   'id': 'name',
      //   'label_name': 'Reporting to',
      //   'field_name': 'display_name',
      //   'related_table': 'employee',
      //   'join_column': 'id',
      //   'primary_table': 'employee',
      //   'primary_table_column': 'reporting_manager_id',
      //   'status': false,
      // },
      // {
      //   'id': 'name',
      //   'label_name': 'Employment Type',
      //   'field_name': 'name',
      //   'related_table': 'employment_types',
      //   'join_column': 'id',
      //   'primary_table': 'employee',
      //   'primary_table_column': 'employment_type_id',
      //   'status': false,
      // },
      {
        'id': 'university_name',
        'label_name': 'Institute Name',
        'field_name': 'university_name',
        'related_table': 'employee_education_details',
        'join_column': 'employee_id',
        'primary_table': 'employee',
        'primary_table_column': 'id',
        'status': false,
      },
      {
        'id': 'name',
        'label_name': 'Degree',
        'field_name': 'name',
        'related_table': 'education_levels',
        'join_column': 'id',
        'primary_table': 'employee_education_details',
        'primary_table_column': 'education_level_id',
        'main_table': 'employee',
        'main_column': 'id',
        'primary_table_main_column': 'employee_id',
        'status': false,
      },
      {
        'id': 'name',
        'label_name': 'Specialization',
        'field_name': 'field_of_study',
        'related_table': 'employee_education_details',
        'join_column': 'employee_id',
        'primary_table': 'employee',
        'primary_table_column': 'id',
        'status': false,
      },
      {
        'id': 'start_date',
        'label_name': 'Start Date',
        'field_name': 'start_date',
        'related_table': 'employee_education_details',
        'join_column': 'employee_id',
        'primary_table': 'employee',
        'primary_table_column': 'id',
        'status': false,
      },
      {
        'id': 'end_date',
        'label_name': 'End Date',
        'field_name': 'end_date',
        'related_table': 'employee_education_details',
        'join_column': 'employee_id',
        'primary_table': 'employee',
        'primary_table_column': 'id',
        'status': false,
      },
      {
        'id': 'state',
        'label_name': 'State',
        'field_name': 'name',
        'related_table': 'states',
        'join_column': 'id',
        'primary_table': 'employee_education_details',
        'primary_table_column': 'state_id',
        'main_table': 'employee',
        'main_column': 'id',
        'primary_table_main_column': 'employee_id',
        'status': false,
      },
      {
        'id': 'country',
        'label_name': 'Country',
        'field_name': 'name',
        'related_table': 'countries',
        'join_column': 'id',
        'primary_table': 'employee_education_details',
        'primary_table_column': 'country_id',
        'main_table': 'employee',
        'main_column': 'id',
        'primary_table_main_column': 'employee_id',
        'status': false,
      },
    ],
  },
  {
    'name': 'Employees Skills',
    'table_name': 'employee',
    'data': [
      {
        'id': 'reference_id',
        'label_name': 'Reference ID',
        'field_name': 'reference_id',
        'related_table': 'employee',
        'status': true,
      },
      {
        'id': 'name',
        'label_name': 'Skill',
        'field_name': 'name',
        'related_table': 'skills',
        'join_column': 'id',
        'primary_table': 'employee_skill_details',
        'primary_table_column': 'skill_id',
        'main_table': 'employee',
        'main_column': 'id',
        'primary_table_main_column': 'employee_id',
        'status': false,
      },
      {
        'id': 'experience_years',
        'label_name': 'Years of Experience',
        'field_name': 'experience_years',
        'related_table': 'employee_skill_details',
        'join_column': 'employee_id',
        'primary_table': 'employee',
        'primary_table_column': 'id',
        'status': false,
      },
      {
        'id': 'expertise',
        'label_name': 'Expertise',
        'field_name': 'expertise',
        'related_table': 'employee_skill_details',
        'join_column': 'employee_id',
        'primary_table': 'employee',
        'primary_table_column': 'id',
        'status': false,
      },
      {
        'id': 'certification',
        'label_name': 'Certification ID or Link',
        'field_name': 'certification',
        'related_table': 'employee_skill_details',
        'join_column': 'employee_id',
        'primary_table': 'employee',
        'primary_table_column': 'id',
        'status': false,
      },
      {
        'id': 'certification_date',
        'label_name': 'Certified Date',
        'field_name': 'certification_date',
        'related_table': 'employee_skill_details',
        'join_column': 'employee_id',
        'primary_table': 'employee',
        'primary_table_column': 'id',
        'status': false,
      },
      {
        'id': 'certification_status',
        'label_name': 'Certification Status',
        'field_name': 'certification_status',
        'related_table': 'employee_skill_details',
        'join_column': 'employee_id',
        'primary_table': 'employee',
        'primary_table_column': 'id',
        'status': false,
      },
    ],
  },
  {
    'name': 'Employees Documents',
    'table_name': 'employee',
    'data': [
      {
        'id': 'reference_id',
        'label_name': 'Reference ID',
        'field_name': 'reference_id',
        'related_table': 'employee',
        'status': true,
      },
      {
        'id': 'name',
        'label_name': 'Document Type',
        'field_name': 'name',
        'related_table': 'document_types',
        'join_column': 'id',
        'primary_table': 'employee_personal_documents',
        'primary_table_column': 'document_type_id',
        'main_table': 'employee',
        'main_column': 'id',
        'primary_table_main_column': 'employee_id',
        'status': false,
      },
      {
        'id': 'document_number',
        'label_name': 'Document Number',
        'field_name': 'document_number',
        'related_table': 'employee_personal_documents',
        'join_column': 'employee_id',
        'primary_table': 'employee',
        'primary_table_column': 'id',
        'status': false,
      },
      {
        'id': 'valid_from',
        'label_name': 'Valid from',
        'field_name': 'valid_from',
        'related_table': 'employee_personal_documents',
        'join_column': 'employee_id',
        'primary_table': 'employee',
        'primary_table_column': 'id',
        'status': false,
      },
      {
        'id': 'valid_till',
        'label_name': 'Valid till',
        'field_name': 'valid_till',
        'related_table': 'employee_personal_documents',
        'join_column': 'employee_id',
        'primary_table': 'employee',
        'primary_table_column': 'id',
        'status': false,
      },
      {
        'id': 'status',
        'label_name': 'Document Status',
        'field_name': 'status',
        'related_table': 'employee_personal_documents',
        'join_column': 'employee_id',
        'primary_table': 'employee',
        'primary_table_column': 'id',
        'status': false,
      },
    ],
  },
  {
    'name': 'Emergency Contact Info',
    'table_name': 'employee',
    'data': [
      {
        'id': 'reference_id',
        'label_name': 'Reference ID',
        'field_name': 'reference_id',
        'related_table': 'employee',
        'status': true,
      },
      // {
      //   'id': 'id',
      //   'label_name': 'Employee ID',
      //   'field_name': 'id',
      //   'related_table': 'employee',
      //   'status': false,
      // },
      {
        'id': 'display_name',
        'label_name': 'Employee Name',
        'field_name': 'display_name',
        'related_table': 'employee',
        'status': false,
      },
      // {
      //   'id': 'name',
      //   'label_name': 'Department',
      //   'field_name': 'name',
      //   'related_table': 'departments',
      //   'join_column': 'id',
      //   'primary_table': 'employee',
      //   'primary_table_column': 'department_id',
      //   'status': false,
      // },
      // {
      //   'id': 'name',
      //   'label_name': 'Reporting to',
      //   'field_name': 'display_name',
      //   'related_table': 'employee',
      //   'join_column': 'id',
      //   'primary_table': 'employee',
      //   'primary_table_column': 'reporting_manager_id',
      //   'status': false,
      // },
      // {
      //   'id': 'name',
      //   'label_name': 'Employment Type',
      //   'field_name': 'name',
      //   'related_table': 'employment_types',
      //   'join_column': 'id',
      //   'primary_table': 'employee',
      //   'primary_table_column': 'employment_type_id',
      //   'status': false,
      // },
      {
        'id': 'name',
        'label_name': 'Name',
        'field_name': 'name',
        'related_table': 'emergency_contact_information',
        'join_column': 'employee_id',
        'primary_table': 'employee',
        'primary_table_column': 'id',
        'status': false,
      },
      {
        'id': 'name',
        'label_name': 'Relation Type',
        'field_name': 'name',
        'related_table': 'relationship_types',
        'join_column': 'id',
        'primary_table': 'emergency_contact_information',
        'primary_table_column': 'relationship_id',
        'main_table': 'employee',
        'main_column': 'id',
        'primary_table_main_column': 'employee_id',
        'status': false,
      },
      {
        'id': 'contact_number',
        'label_name': 'Contact Number',
        'field_name': 'contact_number ',
        'related_table': 'emergency_contact_information',
        'join_column': 'employee_id',
        'primary_table': 'employee',
        'primary_table_column': 'id',
        'status': false,
      },
      {
        'id': 'email_id',
        'label_name': 'Email Id',
        'field_name': 'email_id',
        'related_table': 'emergency_contact_information',
        'join_column': 'employee_id',
        'primary_table': 'employee',
        'primary_table_column': 'id',
        'status': false,
      },

      {
        'id': 'address_1',
        'label_name': 'Address One',
        'field_name': 'address_1',
        'related_table': 'emergency_contact_information',
        'join_column': 'employee_id',
        'primary_table': 'employee',
        'primary_table_column': 'id',
        'status': false,
      },
      {
        'id': 'address_2',
        'label_name': 'Address Two',
        'field_name': 'address_2',
        'related_table': 'emergency_contact_information',
        'join_column': 'employee_id',
        'primary_table': 'employee',
        'primary_table_column': 'id',
        'status': false,
      },
      {
        'id': 'city',
        'label_name': 'City',
        'field_name': 'city',
        'related_table': 'emergency_contact_information',
        'join_column': 'employee_id',
        'primary_table': 'employee',
        'primary_table_column': 'id',
        'status': false,
      },
      {
        'id': 'state',
        'label_name': 'State',
        'field_name': 'name',
        'related_table': 'states',
        'join_column': 'id',
        'primary_table': 'emergency_contact_information',
        'primary_table_column': 'state_id',
        'main_table': 'employee',
        'main_column': 'id',
        'primary_table_main_column': 'employee_id',
        'status': false,
      },
      {
        'id': 'country',
        'label_name': 'Country',
        'field_name': 'name',
        'related_table': 'countries',
        'join_column': 'id',
        'primary_table': 'emergency_contact_information',
        'primary_table_column': 'country_id',
        'main_table': 'employee',
        'main_column': 'id',
        'primary_table_main_column': 'employee_id',
        'status': false,
      },
      {
        'id': 'zipcode',
        'label_name': 'Zipcode',
        'field_name': 'zip_code',
        'related_table': 'emergency_contact_information',
        'join_column': 'employee_id',
        'primary_table': 'employee',
        'primary_table_column': 'id',
        'status': false,
      },
    ],
  },
];


module.exports = { employeeJson };