const formFields = [
  {
    id: 1,
    name: 'First Name',
    column: 'first_name',
    slug: 'employee_form',
    is_editable: false,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 2,
    name: 'Middle Name',
    column: 'middle_name',
    slug: 'employee_form',
    is_editable: false,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 3,
    name: 'Last Name',
    column: 'last_name',
    slug: 'employee_form',
    is_editable: false,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 4,
    name: 'Email ID',
    column: 'email_id',
    slug: 'employee_form',
    is_editable: false,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 5,
    name: 'Alternate Email Id',
    column: 'alternate_email_id',
    slug: 'employee_form',
    is_editable: true,
    is_required: false,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 6,
    name: 'Date of Birth',
    column: 'dob',
    slug: 'employee_form',
    is_editable: false,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 7,
    name: 'Gender',
    column: 'gender',
    slug: 'employee_form',
    is_editable: false,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 8,
    name: 'Contact Number',
    column: 'contact_number',
    slug: 'employee_form',
    is_editable: false,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 9,
    name: 'Alternate Contact Number',
    column: 'alternate_contact_number',
    slug: 'employee_form',
    is_editable: true,
    is_required: false,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 10,
    name: 'Address Line 1',
    column: 'address_line_one',
    slug: 'employee_form',
    is_editable: false,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 11,
    name: 'Address Line 2',
    column: 'address_line_two',
    slug: 'employee_form',
    is_editable: true,
    is_required: false,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 12,
    name: 'Country',
    column: 'country_id',
    slug: 'employee_form',
    is_editable: false,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 13,
    name: 'State',
    column: 'state_id',
    slug: 'employee_form',
    is_editable: false,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 14,
    name: 'City',
    column: 'city',
    slug: 'employee_form',
    is_editable: false,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 15,
    name: 'Zip Code',
    column: 'zip_code',
    slug: 'employee_form',
    is_editable: false,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 16,
    name: 'Employee Reference ID',
    column: 'employee_reference_id',
    slug: 'employee_form',
    is_editable: false,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 17,
    name: 'Employee Type',
    column: 'employment_type_id',
    slug: 'employee_form',
    is_editable: false,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 18,
    name: 'Date of Joining',
    column: 'date_of_joining',
    slug: 'employee_form',
    is_editable: false,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 19,
    name: 'Employee Category',
    column: 'employment_category_id',
    slug: 'employee_form',
    is_editable: false,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 20,
    name: 'SSN',
    column: 'ssn',
    slug: 'employee_form',
    is_editable: true,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 21,
    name: 'Department',
    column: 'department_id',
    slug: 'employee_form',
    is_editable: true,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 22,
    name: 'Team',
    column: 'team_id',
    slug: 'employee_form',
    is_editable: true,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 23,
    name: 'Is USC',
    column: 'is_usc',
    slug: 'employee_form',
    is_editable: false,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 24,
    name: 'Visa Type',
    column: 'visa_type_id',
    slug: 'employee_form',
    is_editable: false,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 25,
    name: 'Reffered Employee',
    column: 'reffered_employee_id',
    slug: 'employee_form',
    is_editable: true,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 26,
    name: 'Reporting Manager ID',
    column: 'reporting_manager_id',
    slug: 'employee_form',
    is_editable: true,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 27,
    name: 'Enable Login',
    column: 'enable_login',
    slug: 'employee_form',
    is_editable: false,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 28,
    name: 'Referral Source',
    column: 'referral_source',
    slug: 'employee_form',
    is_editable: true,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 29,
    name: 'Referral Source Name',
    column: 'referral_source_name',
    slug: 'employee_form',
    is_editable: true,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 31,
    name: 'Role',
    column: 'role_id',
    slug: 'employee_form',
    is_editable: false,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 32,
    name: 'LinkedIn URL',
    column: 'linkedin_url',
    slug: 'employee_form',
    is_editable: true,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 33,
    name: 'Twitter URL',
    column: 'twitter_url',
    slug: 'employee_form',
    is_editable: true,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 34,
    name: 'Blood Group',
    column: 'blood_group',
    slug: 'employee_form',
    is_editable: true,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 35,
    name: 'Marital Status',
    column: 'marital_status',
    slug: 'employee_form',
    is_editable: true,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 36,
    name: 'Client Name',
    column: 'name',
    slug: 'client_form',
    is_editable: false,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 37,
    name: 'Client Reference ID',
    column: 'reference_id',
    slug: 'client_form',
    is_editable: false,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 41,
    name: 'Address Line One',
    column: 'address_line_one',
    slug: 'client_form',
    is_editable: true,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 42,
    name: 'Address Line Two',
    column: 'address_line_two',
    slug: 'client_form',
    is_editable: true,
    is_required: false,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 43,
    name: 'City',
    column: 'city',
    slug: 'client_form',
    is_editable: true,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 44,
    name: 'State',
    column: 'state_id',
    slug: 'client_form',
    is_editable: true,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 45,
    name: 'Country',
    column: 'country_id',
    slug: 'client_form',
    is_editable: true,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 46,
    name: 'Zipcode',
    column: 'zipcode',
    slug: 'client_form',
    is_editable: true,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 47,
    name: 'Employee Name',
    column: 'employee_id',
    slug: 'placement_form',
    is_editable: true,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 48,
    name: 'Client',
    column: 'client_id',
    slug: 'placement_form',
    is_editable: true,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 49,
    name: 'Client Contact One',
    column: 'client_contact_one_id',
    slug: 'placement_form',
    is_editable: true,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 50,
    name: 'Client Contact Two',
    column: 'client_contact_two_id',
    slug: 'placement_form',
    is_editable: true,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 51,
    name: 'End Client',
    column: 'end_client_id',
    slug: 'placement_form',
    is_editable: true,
    is_required: false,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 52,
    name: 'End CLient Contact One',
    column: 'end_client_contact_one_id',
    slug: 'placement_form',
    is_editable: true,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 53,
    name: 'End CLient Contact Two',
    column: 'end_client_contact_two_id',
    slug: 'placement_form',
    is_editable: true,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 54,
    name: 'Job Title',
    column: 'job_title_id',
    slug: 'placement_form',
    is_editable: true,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 55,
    name: 'Project Name',
    column: 'project_name',
    slug: 'placement_form',
    is_editable: true,
    is_required: false,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 56,
    name: 'Work Email',
    column: 'work_email_id',
    slug: 'placement_form',
    is_editable: true,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 57,
    name: 'Placed Employee ID',
    column: 'placed_employee_id',
    slug: 'placement_form',
    is_editable: true,
    is_required: false,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 58,
    name: 'Notice Period',
    column: 'notice_period',
    slug: 'placement_form',
    is_editable: true,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 59,
    name: 'Start date',
    column: 'start_date',
    slug: 'placement_form',
    is_editable: true,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 60,
    name: 'End date',
    column: 'end_date',
    slug: 'placement_form',
    is_editable: true,
    is_required: false,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 61,
    name: 'Pay Type Configuration',
    column: 'pay_type_configuration_id',
    slug: 'placement_form',
    is_editable: true,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 62,
    name: 'Payroll Configuration Type',
    column: 'payroll_configuration_type',
    slug: 'placement_form',
    is_editable: true,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 63,
    name: 'Pay Type',
    column: 'pay_type',
    slug: 'placement_form',
    is_editable: true,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 64,
    name: 'Pay Value',
    column: 'pay_value',
    slug: 'placement_form',
    is_editable: true,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
  {
    id: 65,
    name: 'Payroll pay',
    column: 'payroll_pay',
    slug: 'placement_form',
    is_editable: true,
    is_required: true,
    is_display: true,
    created_at: new Date(),
  },
];

module.exports = { formFields };