// Default Job Types
const jobTitlesData = [
  {
    name: 'Software Engineer',
    description: 'Software Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Software Developer',
    description: 'Software Developer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Senior Software Engineer',
    description: 'Senior Software Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Assistant Professor',
    description: 'Assistant Professor',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Manager JC',
    description: 'Manager JC',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Architect',
    description: 'Architect',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Associate',
    description: 'Associate',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Data Engineer',
    description: 'Data Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Software Development Engineer II',
    description: 'Software Development Engineer II',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Data Scientist',
    description: 'Data Scientist',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Analyst',
    description: 'Analyst',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Senior Systems Analyst JC',
    description: 'Senior Systems Analyst JC',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Java Developer',
    description: 'Java Developer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },

  {
    name: 'Software Development Engineer I',
    description: 'Software Development Engineer I',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Business Analyst',
    description: 'Business Analyst',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'SR Software Engineer',
    description: 'SR Software Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'SR SQL Database Administrator',
    description: 'SR SQL Database Administrator',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Software Developer Applications',
    description: 'Software Developer Applications',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Project Manager',
    description: 'Project Manager',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Senior Software Developer',
    description: 'Senior Software Developer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Vice President',
    description: 'Vice President',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Software Engineer II',
    description: 'Software Engineer II',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Developer',
    description: 'Developer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Software Development Engineer',
    description: 'Software Development Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Software Engineer III',
    description: 'Software Engineer III',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Data Analyst',
    description: 'Data Analyst',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Devops Engineer',
    description: 'Devops Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Manager',
    description: 'Manager',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Product Manager',
    description: 'Product Manager',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Accountants and Auditors',
    description: 'Accountants and Auditors',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Technology Lead US',
    description: 'Technology Lead US',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Senior Consultant',
    description: 'Senior Consultant',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Application Developer',
    description: 'Application Developer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Staff Software Engineer',
    description: 'Staff Software Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Research Scientist',
    description: 'Research Scientist',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Technical Lead',
    description: 'Technical Lead',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Research Associate',
    description: 'Research Associate',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Programmer Analyst',
    description: 'Programmer Analyst',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Lead Software Engineer',
    description: 'Lead Software Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Mechanical Engineer',
    description: 'Mechanical Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Physical Therapist',
    description: 'Physical Therapist',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Systems Analyst',
    description: 'Systems Analyst',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Senior Data Engineer',
    description: 'Senior Data Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Systems Engineer',
    description: 'Systems Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Consultant',
    description: 'Consultant',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Process Engineer',
    description: 'Process Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Computer Systems Analysts',
    description: 'Computer Systems Analysts',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Senior Associate',
    description: 'Senior Associate',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Component Design Engineer',
    description: 'Component Design Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Project Engineer',
    description: 'Project Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Software Developers Applications Kbgfjg',
    description: 'Software Developers Applications Kbgfjg',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Database Administrator',
    description: 'Database Administrator',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Associate Software Engineer',
    description: 'Associate Software Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Program Manager',
    description: 'Program Manager',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Postdoctoral Fellow',
    description: 'Postdoctoral Fellow',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Computer Systems Analyst',
    description: 'Computer Systems Analyst',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Network Engineer',
    description: 'Network Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Senior Data Scientist',
    description: 'Senior Data Scientist',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Applications Consultant 3',
    description: 'Applications Consultant 3',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Senior Associate JC Computer Systems Engineers',
    description: 'Senior Associate JC Computer Systems Engineers',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Senior Engineer',
    description: 'Senior Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Principal Software Engineer',
    description: 'Principal Software Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Developer User Interface',
    description: 'Developer User Interface',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Senior Manager JC',
    description: 'Senior Manager JC',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Engineering Manager',
    description: 'Engineering Manager',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Salesforce Developer',
    description: 'Salesforce Developer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Business Systems Analyst',
    description: 'Business Systems Analyst',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Medical Technologist',
    description: 'Medical Technologist',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Applications Consultant 2',
    description: 'Applications Consultant 2',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Quality Engineer',
    description: 'Quality Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Research Fellow',
    description: 'Research Fellow',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Technical Program Manager',
    description: 'Technical Program Manager',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Accountant',
    description: 'Accountant',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Software Development Engineer III',
    description: 'Software Development Engineer III',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Postdoctoral Associate',
    description: 'Postdoctoral Associate',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Programmer Analyst II',
    description: 'Programmer Analyst II',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Postdoctoral Research Associate',
    description: 'Postdoctoral Research Associate',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Solution Architect',
    description: 'Solution Architect',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Business Intelligence Analyst',
    description: 'Business Intelligence Analyst',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'SR Software Developer',
    description: 'SR Software Developer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Consultant US',
    description: 'Consultant US',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Financial Analyst',
    description: 'Financial Analyst',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Senior Product Manager',
    description: 'Senior Product Manager',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Electrical Engineer',
    description: 'Electrical Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Technical Architect',
    description: 'Technical Architect',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Machine Learning Engineer',
    description: 'Machine Learning Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Vice President Software Engineer',
    description: 'Vice President Software Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: '.NET Developer',
    description: '.NET Developer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Hospitalist',
    description: 'Hospitalist',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Validation Engineer',
    description: 'Validation Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Postdoctoral Scholar',
    description: 'Postdoctoral Scholar',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Senior Developer',
    description: 'Senior Developer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Project Manager US',
    description: 'Project Manager US',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Design Engineer',
    description: 'Design Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'IT Project Manager',
    description: 'IT Project Manager',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Business Intelligence Engineer II',
    description: 'Business Intelligence Engineer II',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Senior Business Analyst',
    description: 'Senior Business Analyst',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Manager JC Computer Systems Engineers',
    description: 'Manager JC Computer Systems Engineers',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Full Stack Developer',
    description: 'Full Stack Developer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Computer Programmer',
    description: 'Computer Programmer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Data Engineer II',
    description: 'Data Engineer II',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Engineer',
    description: 'Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Senior Manager',
    description: 'Senior Manager',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Manager III Software Development',
    description: 'Manager III Software Development',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Solutions Architect',
    description: 'Solutions Architect',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Manufacturing Engineer',
    description: 'Manufacturing Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Senior Solution Specialist',
    description: 'Senior Solution Specialist',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Product Engineer',
    description: 'Product Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Member of Technical Staff',
    description: 'Member of Technical Staff',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Software Engineering Manager',
    description: 'Software Engineering Manager',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Assistant Vice President',
    description: 'Assistant Vice President',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Designer',
    description: 'Designer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Information Security Analysts Kbgfjg',
    description: 'Information Security Analysts Kbgfjg',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Lead Engineer',
    description: 'Lead Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Financial Analysts Kbgfjg',
    description: 'Financial Analysts Kbgfjg',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Application Engineer',
    description: 'Application Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Data Scientist II',
    description: 'Data Scientist II',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Lead Consultant US',
    description: 'Lead Consultant US',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Dentist',
    description: 'Dentist',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Senior Data Analyst',
    description: 'Senior Data Analyst',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Test Engineer',
    description: 'Test Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Operations Research Analysts Kbgfjg',
    description: 'Operations Research Analysts Kbgfjg',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Analyst Testing',
    description: 'Analyst Testing',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Civil Engineer',
    description: 'Civil Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Software Development Engineer Applications',
    description: 'Software Development Engineer Applications',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Data and Applied Scientist',
    description: 'Data and Applied Scientist',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Staff Engineer',
    description: 'Staff Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Instructor',
    description: 'Instructor',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Clinical Laboratory Scientist',
    description: 'Clinical Laboratory Scientist',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Software Engineer 3',
    description: 'Software Engineer 3',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Software Architect',
    description: 'Software Architect',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Industrial Engineer',
    description: 'Industrial Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Direct Care Professional',
    description: 'Direct Care Professional',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Software Engineer I',
    description: 'Software Engineer I',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Product Designer',
    description: 'Product Designer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Professional Services II',
    description: 'Professional Services II',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Senior Software Engineer Developer',
    description: 'Senior Software Engineer Developer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Technical Test Lead US',
    description: 'Technical Test Lead US',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Physician',
    description: 'Physician',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Solution Specialist',
    description: 'Solution Specialist',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Senior Project Manager US',
    description: 'Senior Project Manager US',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Technical Program Manager III',
    description: 'Technical Program Manager III',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Technology Analyst US',
    description: 'Technology Analyst US',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Software Development Engineer IN Test',
    description: 'Software Development Engineer IN Test',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Data Warehouse Specialist',
    description: 'Data Warehouse Specialist',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Hospitalist Physician',
    description: 'Hospitalist Physician',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Manager Software Engineering',
    description: 'Manager Software Engineering',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Software Engineer 2',
    description: 'Software Engineer 2',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'ETL Developer',
    description: 'ETL Developer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Advisory Senior Consultant',
    description: 'Advisory Senior Consultant',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Site Reliability Engineer',
    description: 'Site Reliability Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Software Quality Assurance Engineer',
    description: 'Software Quality Assurance Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Software Application Developer',
    description: 'Software Application Developer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Scientist',
    description: 'Scientist',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'QA Engineer',
    description: 'QA Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Technical Program Manager II',
    description: 'Technical Program Manager II',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Market Research Analyst',
    description: 'Market Research Analyst',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Postdoctoral Research Fellow',
    description: 'Postdoctoral Research Fellow',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'SR Data Engineer',
    description: 'SR Data Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Software Test Engineer',
    description: 'Software Test Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Hardware Engineer',
    description: 'Hardware Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'SAP Consultant',
    description: 'SAP Consultant',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Lecturer',
    description: 'Lecturer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Senior Software Development Engineer',
    description: 'Senior Software Development Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Quality Assurance Engineer II',
    description: 'Quality Assurance Engineer II',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Computer Systems Analyst 3',
    description: 'Computer Systems Analyst 3',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Technical Project Manager',
    description: 'Technical Project Manager',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Advanced Software Developer',
    description: 'Advanced Software Developer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Applied Scientist II',
    description: 'Applied Scientist II',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Scrum Master',
    description: 'Scrum Master',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Component Design Engineer',
    description: 'Component Design Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Technical Support Engineer',
    description: 'Technical Support Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Director',
    description: 'Director',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Principal Consultant',
    description: 'Principal Consultant',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Staff Accountant',
    description: 'Staff Accountant',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Silicon Engineer',
    description: 'Silicon Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Architectural Designer',
    description: 'Architectural Designer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Product Manager III Technical',
    description: 'Product Manager III Technical',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Technology Architect US',
    description: 'Technology Architect US',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Senior Java Developer',
    description: 'Senior Java Developer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'System Administrator',
    description: 'System Administrator',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Computer and Information Systems Managers',
    description: 'Computer and Information Systems Managers',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Program Manager II',
    description: 'Program Manager II',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Principal Software Engineer Developer',
    description: 'Principal Software Engineer Developer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Technical Consultant',
    description: 'Technical Consultant',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Business Analyst II',
    description: 'Business Analyst II',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'System Architect III',
    description: 'System Architect III',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Senior Systems Engineer',
    description: 'Senior Systems Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Program Manager III',
    description: 'Program Manager III',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Senior Devops Engineer',
    description: 'Senior Devops Engineer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Teacher',
    description: 'Teacher',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Research Assistant Professor',
    description: 'Research Assistant Professor',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Senior Program Manager',
    description: 'Senior Program Manager',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Associate Professor',
    description: 'Associate Professor',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'UI Developer',
    description: 'UI Developer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Associate Research Scientist',
    description: 'Associate Research Scientist',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Management Analyst',
    description: 'Management Analyst',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Product Manager III',
    description: 'Product Manager III',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Software Developer II',
    description: 'Software Developer II',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Applications Developer',
    description: 'Applications Developer',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Software Engineering Smts',
    description: 'Software Engineering Smts',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    created_by: null,
  },
];

const jobTitlesDataSeed = async (tenant) => {
  await tenant('job_titles').insert(jobTitlesData);
};

module.exports = jobTitlesDataSeed;