/**Dont't edit this information
 * Default permissions
 */
const permissionsData = [
  {
    module_id: 1,
    name: 'Create',
    slug: 'employee_create',
    description: 'Employee Create Permission',
    created_at: new Date(),
  },
  {
    module_id: 1,
    name: 'Edit',
    slug: 'employee_edit',
    description: 'Employee Edit Permission',
    created_at: new Date(),
  },
  {
    module_id: 1,
    name: 'View',
    slug: 'employee_view',
    description: 'Employee View Permission',
    created_at: new Date(),
  },
  {
    module_id: 1,
    name: 'Delete',
    slug: 'employee_delete',
    description: 'Employee Delete Permission',
    created_at: new Date(),
  },
  {
    module_id: 1,
    name: 'Additional Permissions',
    slug: 'employee_additional_permissions',
    description: 'Employee Additional Permission',
    created_at: new Date(),
  },
  {
    module_id: 1,
    parent_slug: 'employee_additional_permissions',
    name: 'Inactive/Active',
    slug: 'employee_active_inactive',
    description: 'Employee Inactive/Active Permission',
    created_at: new Date(),
  },
  {
    module_id: 1,
    parent_slug: 'employee_additional_permissions',
    name: 'Disable/Enable',
    slug: 'employee_disable_enable',
    description: 'Employee Disable/Enable Permission',
    created_at: new Date(),
  },
  {
    module_id: 1,
    parent_slug: 'employee_additional_permissions',
    name: 'e-Verify',
    slug: 'employee_everification',
    description: 'Employee E-Verification',
    created_at: new Date(),
  },
  {
    module_id: 1,
    parent_slug: 'employee_additional_permissions',
    name: 'Add/Edit Bank Details',
    slug: 'employee_add_edit_bank',
    description: 'Employee Add/Edit Bank Details',
    created_at: new Date(),
  },
  {
    module_id: 1,
    parent_slug: 'employee_additional_permissions',
    name: 'Add/Edit PayRoll Settings',
    slug: 'employee_add_edit_payroll_settings',
    description: 'Employee Add/Edit PayRoll Settings',
    created_at: new Date(),
  },
  {
    module_id: 1,
    parent_slug: 'employee_additional_permissions',
    name: 'Add/Edit Pay Configuration',
    slug: 'employee_add_edit_payconfig',
    description: 'Employee Add/Edit Pay Configuration',
    created_at: new Date(),
  },
  {
    module_id: 1,
    parent_slug: 'employee_additional_permissions',
    name: 'Export',
    slug: 'employee_export',
    description: 'Employee Export',
    created_at: new Date(),
  },
  {
    module_id: 1,
    parent_slug: 'employee_additional_permissions',
    name: 'Import',
    slug: 'employee_import',
    description: 'Employee Import',
    created_at: new Date(),
  },
  {
    module_id: 2,
    name: 'Create',
    slug: 'client_create',
    description: 'Client Create Permission',
    created_at: new Date(),
  },
  {
    module_id: 2,
    name: 'Edit',
    slug: 'client_edit',
    description: 'Client Edit Permission',
    created_at: new Date(),
  },
  {
    module_id: 2,
    name: 'View',
    slug: 'client_view',
    description: 'Client View Permission',
    created_at: new Date(),
  },
  {
    module_id: 2,
    name: 'Delete',
    slug: 'client_delete',
    description: 'Client Delete Permission',
    created_at: new Date(),
  },
  {
    module_id: 2,
    name: 'Additional Permissions',
    slug: 'client_additional_permissions',
    description: 'Client Additional Permission',
    created_at: new Date(),
  },
  {
    module_id: 2,
    parent_slug: 'client_additional_permissions',
    name: 'Overview',
    slug: 'client_overview',
    description: 'Client Overview Permission',
    created_at: new Date(),
  },
  {
    module_id: 2,
    parent_slug: 'client_additional_permissions',
    name: 'Comments',
    slug: 'client_comments',
    description: 'Client Comments Permission',
    created_at: new Date(),
  },
  {
    module_id: 2,
    parent_slug: 'client_additional_permissions',
    name: 'Transactions',
    slug: 'client_transactions',
    description: 'Client Transactions Permission',
    created_at: new Date(),
  },
  {
    module_id: 2,
    parent_slug: 'client_additional_permissions',
    name: 'Statement',
    slug: 'client_statement',
    description: 'Client Statement Permission',
    created_at: new Date(),
  },
  {
    module_id: 2,
    parent_slug: 'client_additional_permissions',
    name: 'Export',
    slug: 'client_export',
    description: 'Client Export',
    created_at: new Date(),
  },
  {
    module_id: 2,
    parent_slug: 'client_additional_permissions',
    name: 'Import',
    slug: 'client_import',
    description: 'Client Import',
    created_at: new Date(),
  },
  {
    module_id: 3,
    name: 'Create',
    slug: 'end_client_create',
    description: 'End Client Create Permission',
    created_at: new Date(),
  },
  {
    module_id: 3,
    name: 'Edit',
    slug: 'end_client_edit',
    description: 'End Client Edit Permission',
    created_at: new Date(),
  },
  {
    module_id: 3,
    name: 'View',
    slug: 'end_client_view',
    description: 'End Client View Permission',
    created_at: new Date(),
  },
  {
    module_id: 3,
    name: 'Delete',
    slug: 'end_client_delete',
    description: 'End Client Delete Permission',
    created_at: new Date(),
  },
  {
    module_id: 3,
    name: 'Additional Permissions',
    slug: 'end_client_additional_permissions',
    description: 'End Client Additional Permissions',
    created_at: new Date(),
  },
  {
    module_id: 3,
    parent_slug: 'end_client_additional_permissions',
    name: 'Export',
    slug: 'end_client_export',
    description: 'End Client Export',
    created_at: new Date(),
  },
  {
    module_id: 3,
    parent_slug: 'end_client_additional_permissions',
    name: 'Import',
    slug: 'end_client_import',
    description: 'End Client Import',
    created_at: new Date(),
  },
  {
    module_id: 4,
    name: 'Create',
    slug: 'placement_create',
    description: 'Placement Create Permission',
    created_at: new Date(),
  },
  {
    module_id: 4,
    name: 'Edit',
    slug: 'placement_edit',
    description: 'Placement Edit Permission',
    created_at: new Date(),
  },
  {
    module_id: 4,
    name: 'View',
    slug: 'placement_view',
    description: 'Placement View Permission',
    created_at: new Date(),
  },
  {
    module_id: 4,
    name: 'Delete',
    slug: 'placement_delete',
    description: 'Placement Delete Permission',
    created_at: new Date(),
  },
  {
    module_id: 4,
    name: 'Additional Permissions',
    slug: 'placement_additional_permissions',
    description: 'Placement Additional Permissions',
    created_at: new Date(),
  },
  {
    module_id: 4,
    parent_slug: 'placement_additional_permissions',
    name: 'Statement',
    slug: 'client_statement',
    description: 'Client Statement Permission',
    created_at: new Date(),
  },
  {
    module_id: 4,
    parent_slug: 'placement_additional_permissions',
    name: 'Export',
    slug: 'placement_export',
    description: 'Placement Export',
    created_at: new Date(),
  },
  {
    module_id: 4,
    parent_slug: 'placement_additional_permissions',
    name: 'Import',
    slug: 'placement_import',
    description: 'Placement Import',
    created_at: new Date(),
  },
  {
    module_id: 5,
    name: 'Create',
    slug: 'timesheet_create',
    description: 'Time Sheet Create Permission',
    created_at: new Date(),
  },
  {
    module_id: 5,
    name: 'Edit',
    slug: 'timesheet_edit',
    description: 'Time Sheet Edit Permission',
    created_at: new Date(),
  },
  {
    module_id: 5,
    name: 'View',
    slug: 'timesheet_view',
    description: 'Time Sheet View Permission',
    created_at: new Date(),
  },
  {
    module_id: 5,
    name: 'Delete',
    slug: 'timesheet_delete',
    description: 'Time Sheet Delete Permission',
    created_at: new Date(),
  },
  {
    module_id: 5,
    name: 'Additional Permissions',
    slug: 'timesheet_additional_permissions',
    description: 'Timesheet Additional Permissions',
    created_at: new Date(),
  },
  {
    module_id: 5,
    parent_slug: 'timesheet_additional_permissions',
    name: 'Export',
    slug: 'timesheet_export',
    description: 'Timesheet Export',
    created_at: new Date(),
  },
  {
    module_id: 5,
    parent_slug: 'timesheet_additional_permissions',
    name: 'Import',
    slug: 'timesheet_import',
    description: 'Timesheet Import',
    created_at: new Date(),
  },
  {
    module_id: 6,
    name: 'Create',
    slug: 'invoice_create',
    description: 'Invoice Create Permission',
    created_at: new Date(),
  },
  {
    module_id: 6,
    name: 'Edit',
    slug: 'invoice_edit',
    description: 'Invoice Edit Permission',
    created_at: new Date(),
  },
  {
    module_id: 6,
    name: 'View',
    slug: 'invoice_view',
    description: 'Invoice View Permission',
    created_at: new Date(),
  },
  {
    module_id: 6,
    name: 'Delete',
    slug: 'invoice_delete',
    description: 'Invoice Delete Permission',
    created_at: new Date(),
  },
  {
    module_id: 6,
    name: 'Additional Permissions',
    slug: 'invoice_additional_permissions',
    description: 'Invoice Additional Permissions',
    created_at: new Date(),
  },
  {
    module_id: 6,
    parent_slug: 'invoice_additional_permissions',
    name: 'Export',
    slug: 'invoice_export',
    description: 'Invoice Export',
    created_at: new Date(),
  },
  {
    module_id: 6,
    parent_slug: 'invoice_additional_permissions',
    name: 'Import',
    slug: 'invoice_import',
    description: 'Invoice Import',
    created_at: new Date(),
  },
  {
    module_id: 6,
    parent_slug: 'invoice_additional_permissions',
    name: 'Void Invoice',
    slug: 'invoice_void',
    description: 'Invoice Void Invoice',
    created_at: new Date(),
  },
  {
    module_id: 7,
    name: 'Create',
    slug: 'employee_self_service_create',
    description: 'Employee Self Service Create Permission',
    created_at: new Date(),
  },
  {
    module_id: 7,
    name: 'Edit',
    slug: 'employee_self_service_edit',
    description: 'Employee Self Service Edit Permission',
    created_at: new Date(),
  },
  {
    module_id: 7,
    name: 'View',
    slug: 'employee_self_service_view',
    description: 'Employee Self Service View Permission',
    created_at: new Date(),
  },
  {
    module_id: 7,
    name: 'Delete',
    slug: 'employee_self_service_delete',
    description: 'Employee Self Service Delete Permission',
    created_at: new Date(),
  },
  {
    module_id: 7,
    name: 'Additional Permissions',
    slug: 'employee_self_service_additional_permissions',
    description: 'Employee Self Service Additional Permissions',
    created_at: new Date(),
  },
  {
    module_id: 7,
    parent_slug: 'employee_self_service_additional_permissions',
    name: 'Re Assignment',
    slug: 'employee_self_service_reassignment',
    description: 'Re-Assign Ticket',
    created_at: new Date(),
  },
  {
    module_id: 8,
    name: 'Create',
    slug: 'expense_management_create',
    description: 'Expense Management Create Permission',
    created_at: new Date(),
  },
  {
    module_id: 8,
    name: 'Edit',
    slug: 'expense_management_edit',
    description: 'Expense Management Edit Permission',
    created_at: new Date(),
  },
  {
    module_id: 8,
    name: 'View',
    slug: 'expense_management_view',
    description: 'Expense Management View Permission',
    created_at: new Date(),
  },
  {
    module_id: 8,
    name: 'Delete',
    slug: 'expense_management_delete',
    description: 'Expense Management Delete Permission',
    created_at: new Date(),
  },
  {
    module_id: 8,
    name: 'Additional Permissions',
    slug: 'expense_management_additional_permissions',
    description: 'Expense Management Additional Permissions',
    created_at: new Date(),
  },
  {
    module_id: 9,
    name: 'Create',
    slug: 'bill_create',
    description: 'Expense Management Create Permission',
    created_at: new Date(),
  },
  {
    module_id: 9,
    name: 'Edit',
    slug: 'bill_edit',
    description: 'Expense Management Edit Permission',
    created_at: new Date(),
  },
  {
    module_id: 9,
    name: 'View',
    slug: 'bill_view',
    description: 'Expense Management View Permission',
    created_at: new Date(),
  },
  {
    module_id: 9,
    name: 'Delete',
    slug: 'bill_delete',
    description: 'Expense Management Delete Permission',
    created_at: new Date(),
  },
  {
    module_id: 9,
    name: 'Additional Permissions',
    slug: 'bill_additional_permissions',
    description: 'Bills Additional Permissions',
    created_at: new Date(),
  },
  {
    module_id: 10,
    name: 'Create',
    slug: 'invoice_payment_create',
    description: 'Invoice Payment Create Permission',
    created_at: new Date(),
  },
  {
    module_id: 10,
    name: 'Edit',
    slug: 'invoice_payment_edit',
    description: 'Invoice Payment Edit Permission',
    created_at: new Date(),
  },
  {
    module_id: 10,
    name: 'View',
    slug: 'invoice_payment_view',
    description: 'Invoice Payment View Permission',
    created_at: new Date(),
  },
  {
    module_id: 10,
    name: 'Delete',
    slug: 'invoice_payment_delete',
    description: 'Invoice Payment Delete Permission',
    created_at: new Date(),
  },
  {
    module_id: 10,
    name: 'Delete',
    slug: 'invoice_payment_delete',
    description: 'Invoice Payment Delete Permission',
    created_at: new Date(),
  },
  {
    module_id: 10,
    name: 'Invoice Payment Additional Permissions',
    slug: 'invoice_payment_additional_permissions',
    description: 'Invoice Payment Additional Permission',
    created_at: new Date(),
  },
  {
    module_id: 6,
    parent_slug: 'payment_additional_permissions',
    name: 'Export',
    slug: 'payment_export',
    description: 'Payment Export',
    created_at: new Date(),
  },
  {
    module_id: 6,
    parent_slug: 'payment_additional_permissions',
    name: 'Import',
    slug: 'payment_import',
    description: 'Payment Import',
    created_at: new Date(),
  },
  {
    module_id: 11,
    name: 'Dashboard',
    slug: 'dashboard',
    description: 'Main Dashboard Permission',
    created_at: new Date(),
  },
  {
    module_id: 12,
    name: 'Create',
    slug: 'configurations_create',
    description: 'Configuration Create Permission',
    created_at: new Date(),
  },
  {
    module_id: 12,
    name: 'Edit',
    slug: 'configurations_edit',
    description: 'Configuration Edit Permission',
    created_at: new Date(),
  },
  {
    module_id: 12,
    name: 'View',
    slug: 'configurations_view',
    description: 'Configuration View Permission',
    created_at: new Date(),
  },
  {
    module_id: 12,
    name: 'Delete',
    slug: 'configurations_delete',
    description: 'Configuration Delete Permission',
    created_at: new Date(),
  },
  {
    module_id: 12,
    name: 'Additional Permissions',
    slug: 'configurations_additional_permissions',
    description: 'Configuration Additional Permission',
    created_at: new Date(),
  },
  {
    module_id: 12,
    parent_slug: 'configurations_additional_permissions',
    name: 'Organization',
    slug: 'configuration_organization',
    description: 'Organization in configuration module',
    created_at: new Date(),
  },
  {
    module_id: 12,
    parent_slug: 'configurations_additional_permissions',
    name: 'Employee',
    slug: 'configuration_employee',
    description: 'Employee in configuration module',
    created_at: new Date(),
  },
  {
    module_id: 12,
    parent_slug: 'configurations_additional_permissions',
    name: 'Placement',
    slug: 'configuration_placement',
    description: 'Placement in configuration module',
    created_at: new Date(),
  },
  {
    module_id: 12,
    parent_slug: 'configurations_additional_permissions',
    name: 'Timesheet',
    slug: 'configuration_timesheet',
    description: 'Timesheet in configuration module',
    created_at: new Date(),
  },
  {
    module_id: 12,
    parent_slug: 'configurations_additional_permissions',
    name: 'Invoices',
    slug: 'configuration_invoice',
    description: 'Invoice in configuration module',
    created_at: new Date(),
  },
  {
    module_id: 12,
    parent_slug: 'configurations_additional_permissions',
    name: 'Employee Self Serviec',
    slug: 'configuration_employee_self_service_types',
    description: 'Employee Self Serviec in configuration module',
    created_at: new Date(),
  },
  {
    module_id: 12,
    parent_slug: 'configurations_additional_permissions',
    name: 'Clients',
    slug: 'configuration_client',
    description: 'Clients Self Serviec in configuration module',
    created_at: new Date(),
  },
  {
    module_id: 12,
    parent_slug: 'configurations_additional_permissions',
    name: 'Expense Management',
    slug: 'configuration_expense_management_types',
    description: 'Expense Management in configuration module',
    created_at: new Date(),
  },
  {
    module_id: 12,
    parent_slug: 'configurations_additional_permissions',
    name: 'Role',
    slug: 'configuration_role',
    description: 'Role in configuration module',
    created_at: new Date(),
  },
  {
    module_id: 12,
    parent_slug: 'configurations_additional_permissions',
    name: 'Templates',
    slug: 'configuration_template',
    description: 'Templates in configuration module',
    created_at: new Date(),
  },
  {
    module_id: 12,
    parent_slug: 'configurations_additional_permissions',
    name: 'Reminder',
    slug: 'configuration_reminder',
    description: 'Reminder in configuration module',
    created_at: new Date(),
  },
  {
    module_id: 12,
    parent_slug: 'configurations_additional_permissions',
    name: 'Group',
    slug: 'configuration_group',
    description: 'Group in configuration module',
    created_at: new Date(),
  },
  {
    module_id: 12,
    parent_slug: 'configurations_additional_permissions',
    name: 'Notification',
    slug: 'configuration_notification',
    description: 'Notification in configuration module',
    created_at: new Date(),
  },
  {
    module_id: 13,
    name: 'Create',
    slug: 'payroll_create',
    description: 'Payroll Create Permission',
    created_at: new Date(),
  },
  {
    module_id: 13,
    name: 'Edit',
    slug: 'payroll_edit',
    description: 'Payroll Edit Permission',
    created_at: new Date(),
  },
  {
    module_id: 13,
    name: 'View',
    slug: 'payroll_view',
    description: 'Payroll View Permission',
    created_at: new Date(),
  },
  {
    module_id: 13,
    name: 'Delete',
    slug: 'payroll_delete',
    description: 'Payroll Delete Permission',
    created_at: new Date(),
  },
  {
    module_id: 13,
    name: 'Additional Permissions',
    slug: 'payroll_additional_permissions',
    description: 'Payroll Additional Permission',
    created_at: new Date(),
  },
  {
    module_id: 14,
    name: 'Create',
    slug: 'balance_sheet_create',
    description: 'Balance Sheet Create Permission',
    created_at: new Date(),
  },
  {
    module_id: 14,
    name: 'Edit',
    slug: 'balance_sheet_edit',
    description: 'Balance Sheet Edit Permission',
    created_at: new Date(),
  },
  {
    module_id: 14,
    name: 'View',
    slug: 'balance_sheet_view',
    description: 'Balance Sheet View Permission',
    created_at: new Date(),
  },
  {
    module_id: 14,
    name: 'Delete',
    slug: 'balance_sheet_delete',
    description: 'Balance Sheet Delete Permission',
    created_at: new Date(),
  },
  {
    module_id: 14,
    name: 'Additional Permissions',
    slug: 'balance_sheet_additional_permissions',
    description: 'Balance Sheet Additional Permission',
    created_at: new Date(),
  },

  {
    module_id: 15,
    name: 'Create',
    slug: 'vendor_create',
    description: 'Vendor Create Permission',
    created_at: new Date(),
  },
  {
    module_id: 15,
    name: 'Edit',
    slug: 'vendor_edit',
    description: 'Vendor Edit Permission',
    created_at: new Date(),
  },
  {
    module_id: 15,
    name: 'View',
    slug: 'vendor_view',
    description: 'Vendor View Permission',
    created_at: new Date(),
  },
  {
    module_id: 15,
    name: 'Delete',
    slug: 'vendor_delete',
    description: 'Vendor Delete Permission',
    created_at: new Date(),
  },
  {
    module_id: 15,
    name: 'Additional Permissions',
    slug: 'vendor_additional_permissions',
    description: 'Vendor Additional Permission',
    created_at: new Date(),
  },
  {
    module_id: 15,
    parent_slug: 'vendor_additional_permissions',
    name: 'Overview',
    slug: 'vendor_overview',
    description: 'Vendor Overview Permission',
    created_at: new Date(),
  },
  {
    module_id: 15,
    parent_slug: 'vendor_additional_permissions',
    name: 'Comments',
    slug: 'vendor_comments',
    description: 'Vendor Comments Permission',
    created_at: new Date(),
  },
  {
    module_id: 15,
    parent_slug: 'vendor_additional_permissions',
    name: 'Transactions',
    slug: 'vendor_transactions',
    description: 'Vendor Transactions Permission',
    created_at: new Date(),
  },
  {
    module_id: 15,
    parent_slug: 'vendor_additional_permissions',
    name: 'Statement',
    slug: 'vendor_statement',
    description: 'Vendor Statement Permission',
    created_at: new Date(),
  },
  {
    module_id: 15,
    parent_slug: 'vendor_additional_permissions',
    name: 'Export',
    slug: 'vendor_export',
    description: 'Vendor Export',
    created_at: new Date(),
  },
  {
    module_id: 15,
    parent_slug: 'vendor_additional_permissions',
    name: 'Import',
    slug: 'vendor_import',
    description: 'Vendor Import',
    created_at: new Date(),
  },
  {
    module_id: 16,
    name: 'Create',
    slug: 'bill_payment_create',
    description: 'Bill Payment Create Permission',
    created_at: new Date(),
  },
  {
    module_id: 16,
    name: 'Edit',
    slug: 'bill_payment_edit',
    description: 'Bill Payment Edit Permission',
    created_at: new Date(),
  },
  {
    module_id: 16,
    name: 'View',
    slug: 'bill_payment_view',
    description: 'Bill Payment View Permission',
    created_at: new Date(),
  },
  {
    module_id: 16,
    name: 'Delete',
    slug: 'bill_payment_delete',
    description: 'Bill Payment Delete Permission',
    created_at: new Date(),
  },
  {
    module_id: 16,
    name: 'Bill Payment Additional Permissions',
    slug: 'bill_payment_additional_permissions',
    description: 'Invoice Payment Additional Permission',
    created_at: new Date(),
  },
];

const permissionDataSeed = async (tenant) => {
  await tenant('permissions').insert(permissionsData);
};

module.exports = permissionDataSeed;