//Default Personal Documents
const  personalDocumentsData = [
  {
    name: 'Driving Licence',
    document_category_id: 4,
    description: 'Driving Licence of the employee',
    is_active: 1,
    is_editable: false,
    created_at: new Date(),
    number_mandatory : true,
    number_display : true,
    valid_from_mandatory : true,
    valid_from_display : true,
    valid_to_mandatory : true,
    valid_to_display : true,
    status_mandatory : true,
    status_display : true,
    upload_mandatory : true,
    upload_display : true,
    created_by: null,
  },
  {
    name: 'SSN',
    document_category_id: 4,
    description: 'SSN of the employee',
    is_active: 1,
    is_editable: false,
    number_mandatory : true,
    number_display : true,
    valid_from_mandatory : true,
    valid_from_display : true,
    valid_to_mandatory : false,
    valid_to_display : false,
    status_mandatory : true,
    status_display : true,
    upload_mandatory : true,
    upload_display : true,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'State ID',
    document_category_id: 4,
    description: 'State ID of the employee',
    is_active: 1,
    is_editable: false,
    number_mandatory : false,
    number_display : true,
    valid_from_mandatory : false,
    valid_from_display : true,
    valid_to_mandatory : false,
    valid_to_display : true,
    status_mandatory : false,
    status_display : true,
    upload_mandatory : false,
    upload_display : true,
    created_at: new Date(),
    created_by: null,
  },
  {
    name: 'Others',
    document_category_id: 4,
    description: 'Other documents of the employee',
    is_active: 1,
    is_editable: false,
    number_mandatory : false,
    number_display : true,
    valid_from_mandatory : false,
    valid_from_display : true,
    valid_to_mandatory : false,
    valid_to_display : true,
    status_mandatory : false,
    status_display : true,
    upload_mandatory : false,
    upload_display : true,
    created_at: new Date(),
    created_by: null,
  },
];

const personalDocumentDataSeed = async (tenant) => {
  await tenant('document_types').insert(personalDocumentsData);
};
module.exports = personalDocumentDataSeed;
